### ISSUE TITLE
Background of generated dynamic image

### ISSUE THREAD

**Issue by lcnnnn** [mvrl/alzheimer-project#1]
Hello, the background of 2D Dynamic image generated by the method is not black, it seems like gray but the pixel value is 0. So I'm wondering if you've been in this situation, and if so, how did you solve it ？

**Comment by xinxing99** [comment]
We don't have your mentioned issue. Do you show your image in Greyscale?

**Comment by lcnnnn** [comment]
yes, the max value is 255 and the min is 0

**Comment by lcnnnn** [comment]
Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?

**Comment by xtrigold** [comment]
> Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?

No, the input should be 1, H, W, D. I used the pytroch default setting on the channel.

**Comment by xinxing99** [comment]
> Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?

I checked my script, I think the output should be DxHxWx1.

**Comment by lcnnnn** [comment]
> > Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?
> 
> No, the input should be 1, H, W, D. I used the pytroch default setting on the channel.

I found that the shape printed in ''ADNI2_MRI_AD_niiData.ipynb'' file is 110,110,110,1，and the code in ''Dynamic_image_Vgg11.ipynb'' file is just "im = np.load(full_path)   im = get_dynamic_image(im) "; Is the shape of "im" 1,H,W,D?

**Comment by xinxing99** [comment]
> Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?

Try RGB to show the image.

**Comment by xinxing99** [comment]
> > > Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?
> > 
> > 
> > No, the input should be 1, H, W, D. I used the pytroch default setting on the channel.
> 
> I found that the shape printed in ''ADNI2_MRI_AD_niiData.ipynb'' file is 110,110,110,1，and the code in ''Dynamic_image_Vgg11.ipynb'' file is just "im = np.load(full_path) im = get_dynamic_image(im) "; Is the shape of "im" 1,H,W,D?

What's your current output size?

**Comment by lcnnnn** [comment]
> > > > Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?
> > > 
> > > 
> > > No, the input should be 1, H, W, D. I used the pytroch default setting on the channel.
> > 
> > 
> > I found that the shape printed in ''ADNI2_MRI_AD_niiData.ipynb'' file is 110,110,110,1，and the code in ''Dynamic_image_Vgg11.ipynb'' file is just "im = np.load(full_path) im = get_dynamic_image(im) "; Is the shape of "im" 1,H,W,D?
> 
> What's your current output size?

Input 3D CT image is D,H,W,1 and output is H,W

**Comment by xinxing99** [comment]
> > > > > Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?
> > > > 
> > > > 
> > > > No, the input should be 1, H, W, D. I used the pytroch default setting on the channel.
> > > 
> > > 
> > > I found that the shape printed in ''ADNI2_MRI_AD_niiData.ipynb'' file is 110,110,110,1，and the code in ''Dynamic_image_Vgg11.ipynb'' file is just "im = np.load(full_path) im = get_dynamic_image(im) "; Is the shape of "im" 1,H,W,D?
> > 
> > 
> > What's your current output size?
> 
> Input 3D CT image is D,H,W,1 and output is H,W

OK, I think the input is correct, try this  
im = np.expand_dims(im,0)
im = np.concatenate([im,im,im], 0)
I extended the image to a RGB-style image (3, H, W). You need to transpose (H, W, 3) then imshow it. Let me know does it work.

**Comment by xinxing99** [comment]
> > > > > > Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?
> > > > > 
> > > > > 
> > > > > No, the input should be 1, H, W, D. I used the pytroch default setting on the channel.
> > > > 
> > > > 
> > > > I found that the shape printed in ''ADNI2_MRI_AD_niiData.ipynb'' file is 110,110,110,1，and the code in ''Dynamic_image_Vgg11.ipynb'' file is just "im = np.load(full_path) im = get_dynamic_image(im) "; Is the shape of "im" 1,H,W,D?
> > > 
> > > 
> > > What's your current output size?
> > 
> > 
> > Input 3D CT image is D,H,W,1 and output is H,W
> 
> OK, I think the input is correct, try this im = np.expand_dims(im,0) im = np.concatenate([im,im,im], 0) I extended the image to a RGB-style image (3, H, W). You need to transpose (H, W, 3) then imshow it. Let me know does it work.

After the dynamic image processing, then condut the aformentioned operation.

**Comment by lcnnnn** [comment]
> > > > > > Did you do the preprocessing of the input image? and is the size of the input 3D image D, H, W, 1?
> > > > > 
> > > > > 
> > > > > No, the input should be 1, H, W, D. I used the pytroch default setting on the channel.
> > > > 
> > > > 
> > > > I found that the shape printed in ''ADNI2_MRI_AD_niiData.ipynb'' file is 110,110,110,1，and the code in ''Dynamic_image_Vgg11.ipynb'' file is just "im = np.load(full_path) im = get_dynamic_image(im) "; Is the shape of "im" 1,H,W,D?
> > > 
> > > 
> > > What's your current output size?
> > 
> > 
> > Input 3D CT image is D,H,W,1 and output is H,W
> 
> OK, I think the input is correct, try this im = np.expand_dims(im,0) im = np.concatenate([im,im,im], 0) I extended the image to a RGB-style image (3, H, W). You need to transpose (H, W, 3) then imshow it. Let me know does it work.

I turned the grayscale map into an RGB image, but it seems that the result has not changed. And I check the value again, founding that the background value is 135, and the value 0 is in other location. Maybe is the reason for CT image, Thank you very much for your guidance.
