### ISSUE TITLE
data

### ISSUE THREAD

**Issue by xinxing277** [mvrl/alzheimer-project#2]
How can I get the data？

**Comment by xinxing99** [comment]
Here is the link to access the data: https://drive.google.com/drive/folders/1BrJKf7Zy-_TYVPXOl58icR4aOeC-vOY9?usp=sharing
Our data is from the ADNI, which is a public website. https://adni.loni.usc.edu/ If you used the data for your publication, please remember to cite them.

**Comment by xinxing277** [comment]
> Here is the link to access the data: https://drive.google.com/drive/folders/1BrJKf7Zy-_TYVPXOl58icR4aOeC-vOY9?usp=sharing Our data is from the ADNI, which is a public website. https://adni.loni.usc.edu/ If you used the data for your publication, please remember to cite them.

Hello! I downloaded the data you provided, and after decompressing it, I encountered an issue with the file not being retrievable when using "ADNI2_MRI_AD_niiData.ipynb" to convert the ".nii" file to ".npy" file.I suspect it's due to the file name being too long. Because after renaming one of the .nii files, I am able to detect the file. Do you have any solutions for this issue?
![图片1](https://github.com/mvrl/alzheimer-project/assets/58331146/ea1b0141-e549-4da6-b6ea-156d925904dc)
